######       Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions. 

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('BuyerRatio.csv')
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [3]:
region_data = data.rename({'Observed Values' : 'Observed_Values'},axis = "columns")
region_data

Observed_Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [4]:
region_data.dtypes

Observed_Values    object
East                int64
West                int64
North               int64
South               int64
dtype: object

In [5]:
East_region = pd.crosstab(index = region_data.Observed_Values,columns = region_data.East)
East_region


East             50   435
Observed_Values          
Females            0    1
Males              1    0

In [6]:
West_region = pd.crosstab(index = region_data.Observed_Values,columns = region_data.East)
West_region


East             50   435
Observed_Values          
Females            0    1
Males              1    0

In [7]:
North_region = pd.crosstab(index = region_data.Observed_Values,columns = region_data.North)
North_region

North            131   1356
Observed_Values            
Females             0     1
Males               1     0

In [8]:
South_region = pd.crosstab(index = region_data.Observed_Values,columns = region_data.South)
South_region

South            70   750
Observed_Values          
Females            0    1
Males              1    0

In [9]:
import scipy.stats as stats
chi_square_tscore,pval,df,exp_table = stats.chi2_contingency(East_region)
print('Chi-square score is {}.\np value is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_tscore,pval,df,exp_table))

Chi-square score is 0.0.
p value is 1.0.
df is 1.
Expected table is 
[[0.5 0.5]
 [0.5 0.5]]


In [10]:
import scipy.stats as stats
chi_square_tscore,pval,df,exp_table = stats.chi2_contingency(West_region)
print('Chi-square score is {}.\np value is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_tscore,pval,df,exp_table))

Chi-square score is 0.0.
p value is 1.0.
df is 1.
Expected table is 
[[0.5 0.5]
 [0.5 0.5]]


In [11]:
import scipy.stats as stats
chi_square_tscore,pval,df,exp_table = stats.chi2_contingency(North_region)
print('Chi-square score is {}.\np value is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_tscore,pval,df,exp_table))

Chi-square score is 0.0.
p value is 1.0.
df is 1.
Expected table is 
[[0.5 0.5]
 [0.5 0.5]]


In [12]:
import scipy.stats as stats
chi_square_tscore,pval,df,exp_table = stats.chi2_contingency(South_region)
print('Chi-square score is {}.\np value is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_tscore,pval,df,exp_table))

Chi-square score is 0.0.
p value is 1.0.
df is 1.
Expected table is 
[[0.5 0.5]
 [0.5 0.5]]


###### The p_value = 1.0 > 0.05 so accept null hypothesis,male-female buyer rations are same 